class Options (int):
    OP_NO_COMPRESSION = 1 << 0
    OP_NO_TICKET = 1 << 1
    OP_NO_SSLv2 = 1 << 2
    OP_NO_SSLv3 = 1 << 3
    OP_NO_ENCRYPT_THEN_MAC = 0x80000
    OP_SAFARI_ECDHE_ECDSA_BUG = 0x40
    OP_DONT_INSERT_EMPTY_FRAGMENTS = 0x800
    OP_TLSEXT_PADDING = 0x10
    OP_LEGACY_SERVER_CONNECT = 0x40
    OP_ALL = OP_SAFARI_ECDHE_ECDSA_BUG | OP_DONT_INSERT_EMPTY_FRAGMENTS | OP_TLSEXT_PADDING | OP_LEGACY_SERVER_CONNECT

class VerifyMode (int):
    CERT_NONE = 0
    CERT_OPTIONAL = 1
    CERT_REQUIRED = 2